// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_lloyd_kmeans
List cpp_lloyd_kmeans(NumericMatrix data, int num_clusters, double threshold, int num_iterations, std::string init_type, int seed, bool with_labels);
RcppExport SEXP _geokmeans_cpp_lloyd_kmeans(SEXP dataSEXP, SEXP num_clustersSEXP, SEXP thresholdSEXP, SEXP num_iterationsSEXP, SEXP init_typeSEXP, SEXP seedSEXP, SEXP with_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_clusters(num_clustersSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type num_iterations(num_iterationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type init_type(init_typeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type with_labels(with_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lloyd_kmeans(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_elkan_kmeans
List cpp_elkan_kmeans(NumericMatrix data, int num_clusters, double threshold, int num_iterations, std::string init_type, int seed, bool with_labels);
RcppExport SEXP _geokmeans_cpp_elkan_kmeans(SEXP dataSEXP, SEXP num_clustersSEXP, SEXP thresholdSEXP, SEXP num_iterationsSEXP, SEXP init_typeSEXP, SEXP seedSEXP, SEXP with_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_clusters(num_clustersSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type num_iterations(num_iterationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type init_type(init_typeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type with_labels(with_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_elkan_kmeans(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hamerly_kmeans
List cpp_hamerly_kmeans(NumericMatrix data, int num_clusters, double threshold, int num_iterations, std::string init_type, int seed, bool with_labels);
RcppExport SEXP _geokmeans_cpp_hamerly_kmeans(SEXP dataSEXP, SEXP num_clustersSEXP, SEXP thresholdSEXP, SEXP num_iterationsSEXP, SEXP init_typeSEXP, SEXP seedSEXP, SEXP with_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_clusters(num_clustersSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type num_iterations(num_iterationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type init_type(init_typeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type with_labels(with_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hamerly_kmeans(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_annulus_kmeans
List cpp_annulus_kmeans(NumericMatrix data, int num_clusters, double threshold, int num_iterations, std::string init_type, int seed, bool with_labels);
RcppExport SEXP _geokmeans_cpp_annulus_kmeans(SEXP dataSEXP, SEXP num_clustersSEXP, SEXP thresholdSEXP, SEXP num_iterationsSEXP, SEXP init_typeSEXP, SEXP seedSEXP, SEXP with_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_clusters(num_clustersSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type num_iterations(num_iterationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type init_type(init_typeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type with_labels(with_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_annulus_kmeans(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_exponion_kmeans
List cpp_exponion_kmeans(NumericMatrix data, int num_clusters, double threshold, int num_iterations, std::string init_type, int seed, bool with_labels);
RcppExport SEXP _geokmeans_cpp_exponion_kmeans(SEXP dataSEXP, SEXP num_clustersSEXP, SEXP thresholdSEXP, SEXP num_iterationsSEXP, SEXP init_typeSEXP, SEXP seedSEXP, SEXP with_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_clusters(num_clustersSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type num_iterations(num_iterationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type init_type(init_typeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type with_labels(with_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_exponion_kmeans(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_geo_kmeans
List cpp_geo_kmeans(NumericMatrix data, int num_clusters, double threshold, int num_iterations, std::string init_type, int seed, bool with_labels);
RcppExport SEXP _geokmeans_cpp_geo_kmeans(SEXP dataSEXP, SEXP num_clustersSEXP, SEXP thresholdSEXP, SEXP num_iterationsSEXP, SEXP init_typeSEXP, SEXP seedSEXP, SEXP with_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_clusters(num_clustersSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type num_iterations(num_iterationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type init_type(init_typeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type with_labels(with_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_geo_kmeans(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ball_kmeans
List cpp_ball_kmeans(NumericMatrix data, int num_clusters, double threshold, int num_iterations, std::string init_type, int seed, bool with_labels);
RcppExport SEXP _geokmeans_cpp_ball_kmeans(SEXP dataSEXP, SEXP num_clustersSEXP, SEXP thresholdSEXP, SEXP num_iterationsSEXP, SEXP init_typeSEXP, SEXP seedSEXP, SEXP with_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type num_clusters(num_clustersSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type num_iterations(num_iterationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type init_type(init_typeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type with_labels(with_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ball_kmeans(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geokmeans_cpp_lloyd_kmeans", (DL_FUNC) &_geokmeans_cpp_lloyd_kmeans, 7},
    {"_geokmeans_cpp_elkan_kmeans", (DL_FUNC) &_geokmeans_cpp_elkan_kmeans, 7},
    {"_geokmeans_cpp_hamerly_kmeans", (DL_FUNC) &_geokmeans_cpp_hamerly_kmeans, 7},
    {"_geokmeans_cpp_annulus_kmeans", (DL_FUNC) &_geokmeans_cpp_annulus_kmeans, 7},
    {"_geokmeans_cpp_exponion_kmeans", (DL_FUNC) &_geokmeans_cpp_exponion_kmeans, 7},
    {"_geokmeans_cpp_geo_kmeans", (DL_FUNC) &_geokmeans_cpp_geo_kmeans, 7},
    {"_geokmeans_cpp_ball_kmeans", (DL_FUNC) &_geokmeans_cpp_ball_kmeans, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_geokmeans(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
