# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_lloyd_kmeans <- function(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels) {
    .Call(`_geokmeans_cpp_lloyd_kmeans`, data, num_clusters, threshold, num_iterations, init_type, seed, with_labels)
}

cpp_elkan_kmeans <- function(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels) {
    .Call(`_geokmeans_cpp_elkan_kmeans`, data, num_clusters, threshold, num_iterations, init_type, seed, with_labels)
}

cpp_hamerly_kmeans <- function(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels) {
    .Call(`_geokmeans_cpp_hamerly_kmeans`, data, num_clusters, threshold, num_iterations, init_type, seed, with_labels)
}

cpp_annulus_kmeans <- function(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels) {
    .Call(`_geokmeans_cpp_annulus_kmeans`, data, num_clusters, threshold, num_iterations, init_type, seed, with_labels)
}

cpp_exponion_kmeans <- function(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels) {
    .Call(`_geokmeans_cpp_exponion_kmeans`, data, num_clusters, threshold, num_iterations, init_type, seed, with_labels)
}

cpp_geo_kmeans <- function(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels) {
    .Call(`_geokmeans_cpp_geo_kmeans`, data, num_clusters, threshold, num_iterations, init_type, seed, with_labels)
}

cpp_ball_kmeans <- function(data, num_clusters, threshold, num_iterations, init_type, seed, with_labels) {
    .Call(`_geokmeans_cpp_ball_kmeans`, data, num_clusters, threshold, num_iterations, init_type, seed, with_labels)
}

